Landing/urls.py
from django.urls import include, re_path,path
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Landing.views import LandingClass



app_name = 'Landing'
urlpatterns = [
    path('',LandingClass.as_view(), name = 'landing'),
]

Login/urls.py
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
#from django.contrib import admin

from . import views
from django.contrib.auth import views as auth_views

#VISTAS
#from Login.views import Index

from Login.views import LoginClass
from Landing.views import LandingClass
from Profile.views import ProfileClass
#from Login.views import Landing
#URL QUE MANEJAN LOS PARAMETROS DASHBOARD
app_name = 'Login'

urlpatterns = [

    path('',LoginClass.as_view(), name = 'login'),
]

Profile/urls.py
from django.urls import include, re_path,path
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Profile.views import ProfileClass


app_name = 'Profile'
urlpatterns = [
    path('Profile',ProfileClass.as_view(), name = 'profile')
]

ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('Landing.urls')),
    path('login/', include ('Login.urls')),
    path('profile/', include ('Profile.urls')),
    path('register/', include ('Register.urls')),
    path('logout/',logout_then_login, name='logout')

]

Register/urls.py
from django.urls import include, re_path,path
from django.conf import settings
from django.contrib.auth import views as auth_view
from Register.views import RegisterClass



app_name = 'Register'
urlpatterns = [
    path('',RegisterClass.as_view(), name = 'register'),
]

Landing/models.py
from django.db import models

# Create your models here.

Login/models.py
from django.db import models

# Create your models here.

Profile/models.py
from django.db import models

# Create your models here.

Register/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfile(models.Model):
    #Añadir atributos de user
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #Añadir los demas atributos
    name=models.CharField(max_length=50,null=False);
    age=models.IntegerField(null=False);
    email=models.EmailField(max_length=50,null=False);


    def __str__(self):
        return self.user.username

Register/forms.py
from django.contrib.auth.models import User
from django import forms

ERROR_MESSAGE_USER = {'unique' : 'El Username ya se encuentra registrado', 'invalid' : 'usuario o contraseña incorrecto'}
ERROR_MESSAGE_PASSWORD = {'required' : 'El password es requerido'}
ERROR_MESSAGE_EMAIL = {'invalid' : 'Ingrese un correo valido'}
ERROR_MESSAGE_PHONE = {'invalid' : 'Formato numero incorrecto'}


class RegisterBusinessForm(forms.ModelForm):
    first_name = forms.CharField(label='', required=True)
    last_name = forms.CharField(label='', required=True)
    password = forms.CharField(max_length = 20,required=True, widget = forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD )
    email = forms.CharField( required = True, error_messages = ERROR_MESSAGE_EMAIL)

    def __init__(self, *args, **kwargs):
        super(RegisterBusinessForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update( {'id': 'username_create', 'class': 'form-control', 'placeholder': 'Usuario'} ) # Esto es un input en HTML <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name = "password" required>
        self.fields['first_name'].widget.attrs.update( {'id': 'first_name_create', 'class': 'form-control', 'placeholder': 'Nombre'} )
        self.fields['last_name'].widget.attrs.update( {'id': 'last_name_create', 'class': 'form-control', 'placeholder': 'Apellidos'} )
        self.fields['password'].widget.attrs.update( {'id': 'password_create', 'class': 'form-control', 'placeholder': 'Contraseña'} )
        self.fields['email'].widget.attrs.update( {'id': 'email_create', 'class': 'form-control', 'placeholder': 'Correo Electrónico'} )

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

Landing/views.py
from django.shortcuts import render,redirect
from django.views.generic import View

#IMPORTAR METODO DE AUTENTICACION
from django.contrib.auth import authenticate
 #LLEGA A LA VISTA Y LA EJECUTA

class LandingClass(View):
    templates='landing.html'
    def get(self,request,*args,**kwargs):
        return render(request,self.templates,{})

Login/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from django.contrib.auth import login as login_django

#IMPORTAR METODO DE AUTENTICACION
from django.contrib.auth import authenticate
 #LLEGA A LA VISTA Y LA EJECUTA

class LoginClass(View):
    templates='index2.html'
    #templateOk='dashboard.html'

    def get(self,request, *args,**kwargs,):
        if request.user.is_authenticated:
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('Profile:profile')
        return render(request, self.templates,{})
        # print("aqui esta login")
        # return render(request,self.templates,{})

    def post(self,request,*args,**kwargs,):
        userPost=request.POST['user']
        passwordPost=request.POST['password']
        user_session = authenticate(username = userPost, password = passwordPost)
        #ACÁ LO VALIDO
        if user_session is not None:
            login_django(
                request, user_session
            )
            next_url = request.GET.get('next')
            print("iniciamos1")
            print(user_session.username)
            if next_url:
                print("iniciamos2")
                return redirect(next_url)
            else:
                print("iniciamos3")
                print(user_session.username)
                return redirect('Profile:profile')
        else:
            self.message = 'Usuario o contraseña incorrecto'

        return render(request, self.templates,self.getContext())
        # user_session=authenticate(username=userPost, password=passwordPost)

        # if user_session is not None:
        #     print('si existe')
        #     #return render(request,DashboardClass.templateOk,{})
        #     return redirect('Dashboard:dashboard')
        # else:
        #     print('no existe')
        #     self.message='Usuario o contraseña incorrectos'


        # #pass
        # return render(request,self.templates, self.getContext())

    def getContext(self):
        return{
            'error':self.message,
        }
# def Index (request):
#     return render(request,'index.html',{})

# def Landing (request):
#     return render(request,'landing.html',{})

Profile/views.py
from django.shortcuts import render,redirect
from django.views.generic import View

#IMPORTAR METODO DE AUTENTICACION
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
 #LLEGA A LA VISTA Y LA EJECUTA

class ProfileClass(LoginRequiredMixin,View):
    templates_okidoki = 'profile.html'
    def get (self,request,*args,**kwargs):
        #printn("GET DE DASHBOARD")
        return render(request,self.templates_okidoki,{})
# class DashboardClass(View):
#     templates='dashboard.html'
#     def get(self,request,*args,**kwargs):
#         return render(request,self.templates,{})

Register/views.py
from django.views.generic.edit import FormView
from django.shortcuts import render,redirect
from Register.forms import RegisterBusinessForm

class RegisterClass(FormView):
    template_name = 'register.html'

    # GET
    def get(self, request, *args, **kwargs):
        form = RegisterBusinessForm(request.GET or None)
        context = {
        'form_get' : form
        }
        return render(request, self.template_name, context)

        # POST
    def post(self, request, *args, **kwargs):
        form = RegisterBusinessForm(request.POST or None)

        if form.is_valid():
            self.object = form.save(commit = False)
            self.object.set_password(self.object.password)
            self.object.save()
        return redirect('Login:login')

Landing/templates/landing.html
{%load static%}
<! doctype html />
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <link href="{% static 'styles/style4.css' %}" type="text/css" rel="stylesheet">

    <title>Landing </title>

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}


</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand">Pagina de inicio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- NAV BAR -->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Login:login'%}">Login
                  <span class="sr-only">(current)</span>
                </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Register:register'%}">Register</a>
          </li>
        </ul>
      </div>

      <!-- FIN NAV BAR -->
    </div>
  </nav>

  <!-- CAROUSEL -->
  <header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image: url('{% static 'styles/back_land.jpg' %}')">
          <div class="carousel-caption d-none d-md-block">
            <h2 class="display-4">First Slide</h2>
            <p class="lead">This is a description for the first slide.</p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('{% static 'styles/Image-5.png' %}')">
          <div class="carousel-caption d-none d-md-block">
            <h2 class="display-4">Second Slide</h2>
            <p class="lead">This is a description for the second slide.</p>
          </div>
        </div>
        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('{% static 'styles/Image-6.png' %}')">
          <div class="carousel-caption d-none d-md-block">
            <h2 class="display-4">Third Slide</h2>
            <p class="lead">This is a description for the third slide.</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
      <a class="carousel-control-next" href="" role="button" data-slide="next">
            <span class="sr-only">Next</span>
          </a>
    </div>
  </header>

  <!-- FIN CAROUSEL -->

    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>

<footer>

</footer>

</html>

Login/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Login Form with Avatar Image</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style type="text/css">
	body {
		color: #fff;
		background: #d47677;
	}
	.form-control {
        min-height: 41px;
		background: #fff;
		box-shadow: none !important;
		border-color: #e3e3e3;
	}
	.form-control:focus {
		border-color: #70c5c0;
	}
    .form-control, .btn {
        border-radius: 2px;
    }
	.login-form {
		width: 350px;
		margin: 0 auto;
		padding: 100px 0 30px;
	}
	.login-form form {
		color: #7a7a7a;
		border-radius: 2px;
    	margin-bottom: 15px;
        font-size: 13px;
        background: #ececec;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
        position: relative;
    }
	.login-form h2 {
		font-size: 22px;
        margin: 35px 0 25px;
    }
	.login-form .avatar {
		position: absolute;
		margin: 0 auto;
		left: 0;
		right: 0;
		top: -50px;
		width: 95px;
		height: 95px;
		border-radius: 50%;
		z-index: 9;
		background: #70c5c0;
		padding: 15px;
		box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.1);
	}
	.login-form .avatar img {
		width: 100%;
	}
    .login-form input[type="checkbox"] {
        margin-top: 2px;
    }
    .login-form .btn {
        font-size: 16px;
        font-weight: bold;
		background: #70c5c0;
		border: none;
		margin-bottom: 20px;
    }
	.login-form .btn:hover, .login-form .btn:focus {
		background: #50b8b3;
        outline: none !important;
	}
	.login-form a {
		color: #fff;
		text-decoration: underline;
	}
	.login-form a:hover {
		text-decoration: none;
	}
	.login-form form a {
		color: #7a7a7a;
		text-decoration: none;
	}
	.login-form form a:hover {
		text-decoration: underline;
	}
</style>
</head>
<body>
<div class="login-form">
    <form action="/examples/actions/confirmation.php" method="post">
		<div class="avatar">
			<img src="/examples/images/avatar.png" alt="Avatar">
		</div>
        <h2 class="text-center">Member Login</h2>
        <div class="form-group">
        	<input type="text" class="form-control" name="username" placeholder="Username" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>
        </div>
		<div class="clearfix">
            <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
            <a href="#" class="pull-right">Forgot Password?</a>
        </div>
    </form>
    <p class="text-center small">Don't have an account? <a href="#">Sign up here!</a></p>
</div>
</body>
</html>                            

Login/templates/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <title>Mi primer Login</title>

    <!--JQUERY-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- FRAMEWORK BOOTSTRAP para el estilo de la pagina-->
    {% load bootstrap4 %}
    {% bootstrap_css %}

    <!-- Los iconos tipo Solid de Fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
    <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

    <!-- Nuestro css-->
    <link href="{% static 'styles/styles.css' %}" type="text/css" rel="stylesheet">

</head>
<body>
<div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'Landing:landing'%}">Pagina de inicio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- NAV BAR -->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item active">
            <a class="nav-link">Login
                  <span class="sr-only">(current)</span>
                </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Register:register'%}">Register</a>
          </li>
        </ul>
      </div>

      <!-- FIN NAV BAR -->
    </div>
  </nav>
</div>
<div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-4 formulario">
        <div class="col-12 user-img text-center">
            <img src="{% static 'styles/avatar.png' %}"/>
        </div>
        <form method="POST">
          <!--Inicio cifrado-->
          {% csrf_token %}
          <!--fin cifrado-->
          <div class="form-group text-center">
            <h3>Inicia Sesion</h3>
          </div>
          <!-- Inputs-->
          <!-- AQUI SE CAMBIA COLOR DE TEXTO INPUT -->
          <div class="form-group mx-sm-4 pt-2" id="user-group">
            <input type="text"style="color:black" class="form-control" id="example2"
            aria-describedby="emailHelp" placeholder="Usuario" name="user" required>
          </div>
          <div class="form-group mx-sm-4 pb-2" id="contrasena-group">
            <input type="password" style="color:black" class="form-control" id="example1"
            placeholder="Contraseña" name="password" required>
          </div>
          <div class="form-group mx-sm-4">
            <button type="submit" class="btn btn-block ingresar">Aceptar</button>
            <br>
            {% if error %}
            <br>
            <div class="alert alert-warning" role="alert">
                {{error}}
            </div>
            {% endif %}
        </div>
        </form>
      </div>
    </div>
  </div>
</div>

</body>
</html>

Login/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <title>Mi primer Login</title>

    <!--JQUERY-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- FRAMEWORK BOOTSTRAP para el estilo de la pagina-->
    {% load bootstrap4 %}
    {% bootstrap_css %}

    <!-- Los iconos tipo Solid de Fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
    <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

    <!-- Nuestro css-->
    <link href="{% static 'styles/style.css' %}" type="text/css" rel="stylesheet">

</head>
<body>
    <div class="modal-dialog text-center">
        <div class="col-sm-8 main-section">
            <div class="modal-content">
                <div class="col-12 user-img">
                    <img src="{% static 'styles/avatar.png' %}"/>
                </div>
                <form class="col-12" method="POST">

                <!--Inicio cifrado-->
                {% csrf_token %}
                <!--fin cifrado-->
                  <div class="form-group" style="text-align: center" id="user-group">
                    <input type="text" class="form-control" id="example2"
                    aria-describedby="emailHelp" placeholder="email" name="user" required>
                  </div>

                  <div class="form-group" id="contrasena-group">
                    <input type="password" class="form-control" id="example1"
                    placeholder="password" name="password" required>
                  </div>
                  <div style="text-align: center">
                    <button type="submit" class="btn btn-primary">Aceptar</button>
                    <br>
                    {% if error %}
                    <br>
                    <div class="alert alert-warning" role="alert">
                        {{error}}
                    </div>
                    {% endif %}
                    <a href = "{% url 'Landing:landing'%}">Ir a Landing  </a>
                    <a href = "{% url 'Register:register'%}">Registrarse</a>
                </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

Profile/templates/profile.html
{% load static %}
<! doctype html />
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <link href="{% static 'styles/style3.css' %}" type="text/css" rel="stylesheet">
    <title>Profile</title>


    {% load bootstrap4 %}

    {% bootstrap_css %}



</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'Landing:landing'%}">Pagina de inicio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- NAV BAR -->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <a class="nav-link" href= "{% url 'logout' %}">Cerar Sesion</a>
          </li>
        </ul>
      </div>

      <!-- FIN NAV BAR -->
    </div>
  </nav>

    <div class="cabecera">
      <!-- hola soy header -->
      <div class="div0">
        <img class="user-img2" src="{% static 'styles/adidas.png' %}"/>
      </div>
      <div class="div1">
        <img class="user-img" src="{% static 'styles/logo.png' %}"/>
      </div>

      <!-- Creando div general para los dos divs -->
      <div class="divgeneral">
        <div class="div2">
          <h1 class="estilo1">CLUB ATLETICO RIVER PLATE</h1>
        </div>
        <div class="div3">
          <h1 class="estilo2">Sitio web oficial.</h1>
        </div>
      </div>
      <!-- <div class="user-img">
        <img src="{% static 'styles/logo.png' %}"/>
        <p class="estilo1">CLUB ATLETICO RIVER PLATE</p>
        <br>
        <p class="estilo2">Sitio web oficial.</p>
      </div> -->
    </div>
    <div class="divprofile">
      <div class="divProfile1">
        <p class="estilo3">Bienvenido {{user.username}}</p>
      </div>
    </div>

  <!-- Bienvenida con nombre de usuario -->
  <!-- <h1>{{user.username}} Bienvenido</h1> -->
    <!-- <h1>Hola soy dashboard</h1>
    <br>
    <h1>Bienvenido {{user.username}} </h1>
    <a href= "{% url 'logout' %}">Cerrar Sesion</a> -->
</body>


</html>

Register/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <title>Mi primer Login</title>

    <!--JQUERY-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- FRAMEWORK BOOTSTRAP para el estilo de la pagina-->
    {% load bootstrap4 %}
    {% bootstrap_css %}

    <!-- Los iconos tipo Solid de Fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
    <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

    <!-- Nuestro css-->
    <link href="{% static 'styles/styles.css' %}" type="text/css" rel="stylesheet">

</head>
<body>
<div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'Landing:landing'%}">Pagina de inicio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- NAV BAR -->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Login:login'%}">Login
                  <span class="sr-only">(current)</span>
                </a>
          </li>
          <li class="nav-item">
            <a class="nav-link">Register</a>
          </li>
        </ul>
      </div>

      <!-- FIN NAV BAR -->
    </div>
  </nav>
</div>
<div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-4 formulario">
        <div class="col-12 user-img text-center">
            <img src="{% static 'styles/avatar.png' %}"/>
        </div>
        <form method="POST">
          <div class="form-group text-center">
            <h3>Registra tus datos</h3>
          </div>
          <!--Inicio cifrado-->
          {% csrf_token %}
          <!--fin cifrado-->
          {% if form_get.username.value %}
          {{ form_get.username }}
          {% else %}
          {{ form_get.username }}
          {% endif %}
          <br>
          {% if form_get.first_name.value %}
          {{ form_get.first_name }}
          {% else %}
          {{ form_get.first_name }}
          {% endif %}
          <br>
          {% if form_get.last_name.value %}
          {{ form_get.last_name }}
          {% else %}
          {{ form_get.last_name }}
          {% endif %}
          <br>
          {% if form_get.password.value %}
          {{ form_get.password }}
          {% else %}
          {{ form_get.password }}
          {% endif %}
          <br>
          {% if form_get.email.value %}
          {{ form_get.email }}
          {% else %}
          {{ form_get.email }}
          {% endif %}
          <br>
          <div style="text-align: center">
              <button type="submit" class="btn btn-primary">Registrar</button>
          </div>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>

</body>
</html>